# Generated by Django 4.0.4 on 2022-05-10 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icreate_date', models.DateTimeField()),
                ('imgdata', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucreate_date', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=20)),
                ('typems', models.CharField(max_length=20)),
                ('imgs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.img')),
            ],
        ),
    ]
